version: '3.8'

services:
  coqui-tts:
    build:
      context: .
    ports:
      - "8083:8000"
    volumes:
      - ./:/app
      - ./models:/app/models
      - ./output:/app/output
      - ./reference_voice.wav:/app/reference_audio/reference_voice.wav:ro
    environment:
      - TTS_HOME=/app/models
      - PYTHONUNBUFFERED=1
      - WATCHFILES_FORCE_POLLING=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--reload-dir", "/app"]